-- Custom admin alerts: a fixed set of rules (toggle + per-hour threshold)
-- and an alert feed generated by DB triggers. Forum writes only arrive via
-- the service role (edge function) or security-definer RPCs, both of which
-- bypass the alert tables' RLS, so the triggers always succeed.

create table admin_alert_rules (
  id text primary key check (id in
    ('auto_hidden_heuristic', 'auto_hidden_reports',
     'post_rate_spike', 'report_rate_spike')),
  enabled boolean not null default true,
  -- events per hour; null for non-spike rules
  threshold integer check (threshold > 0),
  updated_at timestamptz not null default now()
);

insert into admin_alert_rules (id, threshold) values
  ('auto_hidden_heuristic', null),
  ('auto_hidden_reports', null),
  ('post_rate_spike', 20),
  ('report_rate_spike', 10);

create table admin_alerts (
  id bigint generated always as identity primary key,
  rule_id text not null references admin_alert_rules (id),
  subject_post_id uuid references forum_posts (id) on delete set null,
  detail jsonb,
  read boolean not null default false,
  created_at timestamptz not null default now()
);

create index admin_alerts_feed_idx on admin_alerts (created_at desc);
create index admin_alerts_dedupe_idx
  on admin_alerts (rule_id, created_at desc) where not read;

alter table admin_alert_rules enable row level security;
alter table admin_alerts enable row level security;
revoke all on admin_alert_rules, admin_alerts from anon, authenticated;

grant select on admin_alert_rules to authenticated;
-- Column-level: rule ids are immutable, only the knobs can change.
grant update (enabled, threshold) on admin_alert_rules to authenticated;
grant select, delete on admin_alerts to authenticated;
grant update (read) on admin_alerts to authenticated;

create policy admin_read on admin_alert_rules
  for select to authenticated using (is_admin());
create policy admin_update on admin_alert_rules
  for update to authenticated using (is_admin()) with check (is_admin());
create policy admin_read on admin_alerts
  for select to authenticated using (is_admin());
create policy admin_update on admin_alerts
  for update to authenticated using (is_admin()) with check (is_admin());
create policy admin_delete on admin_alerts
  for delete to authenticated using (is_admin());

create function admin_alert_rules_touch() returns trigger
language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger admin_alert_rules_touch
  before update on admin_alert_rules
  for each row execute function admin_alert_rules_touch();

-- Heuristic auto-hide alert + post-rate spike. The edge function inserts
-- filtered posts already hidden/spam with hidden_reason='auto_heuristic'.
-- Spike dedupe: no new alert while an unread one of the same rule exists
-- within the last hour.
create function admin_alerts_on_post_insert() returns trigger
language plpgsql as $$
declare
  r admin_alert_rules%rowtype;
  n bigint;
begin
  if new.status <> 'visible' and new.hidden_reason = 'auto_heuristic'
     and exists (select 1 from admin_alert_rules
                  where id = 'auto_hidden_heuristic' and enabled) then
    insert into admin_alerts (rule_id, subject_post_id, detail)
    values ('auto_hidden_heuristic', new.id,
            jsonb_build_object('status', new.status,
                               'spam_score', new.spam_score));
  end if;

  select * into r from admin_alert_rules
   where id = 'post_rate_spike' and enabled and threshold is not null;
  if found then
    select count(*) into n from forum_posts
     where created_at > now() - interval '1 hour';
    if n >= r.threshold and not exists (
         select 1 from admin_alerts
          where rule_id = 'post_rate_spike' and not read
            and created_at > now() - interval '1 hour') then
      insert into admin_alerts (rule_id, detail)
      values ('post_rate_spike',
              jsonb_build_object('count_last_hour', n,
                                 'threshold', r.threshold));
    end if;
  end if;
  return null;
end;
$$;

create trigger forum_posts_admin_alerts
  after insert on forum_posts
  for each row execute function admin_alerts_on_post_insert();

-- Report-threshold auto-hide happens via UPDATE (forum_after_report_insert
-- sets status='hidden', hidden_reason='reports'). Admin hides carry
-- hidden_reason='admin' and correctly do not alert.
create function admin_alerts_on_post_status() returns trigger
language plpgsql as $$
begin
  if old.status = 'visible' and new.status = 'hidden'
     and new.hidden_reason = 'reports'
     and exists (select 1 from admin_alert_rules
                  where id = 'auto_hidden_reports' and enabled) then
    insert into admin_alerts (rule_id, subject_post_id, detail)
    values ('auto_hidden_reports', new.id,
            jsonb_build_object('report_count', new.report_count));
  end if;
  return null;
end;
$$;

create trigger forum_posts_admin_alerts_status
  after update of status on forum_posts
  for each row execute function admin_alerts_on_post_status();

-- Report-rate spike, mirror of the post-rate spike.
create function admin_alerts_on_report_insert() returns trigger
language plpgsql as $$
declare
  r admin_alert_rules%rowtype;
  n bigint;
begin
  select * into r from admin_alert_rules
   where id = 'report_rate_spike' and enabled and threshold is not null;
  if found then
    select count(*) into n from forum_reports
     where created_at > now() - interval '1 hour';
    if n >= r.threshold and not exists (
         select 1 from admin_alerts
          where rule_id = 'report_rate_spike' and not read
            and created_at > now() - interval '1 hour') then
      insert into admin_alerts (rule_id, detail)
      values ('report_rate_spike',
              jsonb_build_object('count_last_hour', n,
                                 'threshold', r.threshold));
    end if;
  end if;
  return null;
end;
$$;

create trigger forum_reports_admin_alerts
  after insert on forum_reports
  for each row execute function admin_alerts_on_report_insert();
